matrix:
- name: Python Source
  sources:
  - '**/*.py'
  aspell:
    lang: en
  pipeline:
  - pyspelling.filters.python:
    comments: true
    docstrings: true
    group_comments: false
    decode_escapes: true
    strings: false
    string_types: fu
- name: markdown
  pipeline:
  - pyspelling.filters.markdown:
  sources:
  - '**/*.md'